name: macOS build
on:
  workflow_call:
jobs:
  build:
    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        runs-on: [macos-13, macos-14]
        include:
          - runs-on: macos-13
            create-distributable: false
          - runs-on: macos-14
            create-distributable: ${{ github.event_name != 'pull_request' }}
            build_variant: universal
    env:
      boost_version: 1.84.0
      BOOST_ROOT: ${{ github.workspace }}/deps/boost-1.84.0
    steps:
      - name: Checkout last commit
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Configure build environment
        run: |
          brew install llvm ninja
          echo "CMAKE_GENERATOR=Ninja"  >> $GITHUB_ENV
          echo "/usr/local/opt/llvm/bin" >> $GITHUB_PATH

      - name: Configure build variant
        if: matrix.build_variant == 'universal'
        run: |
          echo BUILD_UNIVERSAL=1 >> $GITHUB_ENV

      - name: Install Boost
        run: ./install-boost.sh

      - name: Check submodules
        run: git submodule > submodule-status

      - name: Cache dependencies
        id: cache-deps
        uses: actions/cache@v4
        with:
          path: |
            bin
            include
            lib
            share
          key: ${{ runner.os }}-${{ matrix.build_variant || runner.arch }}-deps-${{ hashFiles('submodule-status') }}

      - name: Build dependencies
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: make deps

      - name: Build
        run: make release

      - name: Set version info
        if: matrix.create-distributable
        run: |
          echo "librime ${{ github.ref_name }}" >> version-info.txt
          echo $(git ls-tree HEAD:plugins | awk '$2 == "commit" {print $4,$3}') >> version-info.txt

      - name: Create distributable
        if: matrix.create-distributable
        run: |
          make install
          tar -cjvf rime-TypeDuck-${{ github.ref_name }}-${{ runner.os }}-${{ matrix.build_variant || runner.arch }}.tar.bz2 \
          dist version-info.txt
          tar -cjvf rime-deps-TypeDuck-${{ github.ref_name }}-${{ runner.os }}-${{ matrix.build_variant || runner.arch }}.tar.bz2 \
          --exclude '*/.placeholder' \
          bin include lib share

      - name: Upload artifacts
        if: matrix.create-distributable
        uses: actions/upload-artifact@v4
        with:
          name: artifact-${{ runner.os }}-${{ matrix.build_variant || runner.arch }}
          path: |
            rime-TypeDuck-${{ github.ref_name }}-${{ runner.os }}-${{ matrix.build_variant || runner.arch }}.tar.bz2
            rime-deps-TypeDuck-${{ github.ref_name }}-${{ runner.os }}-${{ matrix.build_variant || runner.arch }}.tar.bz2
