name: Release CI

on:
  workflow_dispatch:
  push:
    tags:
      - '[0-9]+.*'

jobs:
  linux:
    uses: ./.github/workflows/linux-build.yml

  macos:
    uses: ./.github/workflows/macos-build.yml
    with:
      build_variant: '-universal'

  windows:
    uses: ./.github/workflows/windows-build.yml

  release:
    needs: [macos, windows]
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3

      - name: Get version name
        run: |
          echo rime_version="$(git describe --always)" >> $env:GITHUB_ENV

      - name: Create GitHub release
        uses: 'marvinpinto/action-automatic-releases@latest'
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: ${{ env.rime_version }}
          title: "librime for TypeDuck: ${{ env.rime_version }}"
          files: |
            artifact/*
