name: Release CI

on:
  push:
    tags:
      - '**'

jobs:
  linux:
    uses: ./.github/workflows/linux-build.yml

  macos:
    uses: ./.github/workflows/macos-build.yml
    with:
      build_variant: '-universal'

  windows:
    uses: ./.github/workflows/windows-build.yml

  release:
    needs: [macos, windows]
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3

      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        with:
          name: "librime for TypeDuck: ${{ github.ref_name }}"
          files: |
            artifact/*
