name: Windows build
on:
  workflow_call:
jobs:
  build:
    runs-on: windows-latest
    env:
      boost_version: 1.83.0
      BOOST_ROOT: ${{ github.workspace }}\deps\boost_1_83_0
    steps:
      - name: Checkout last commit
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Configure build environment
        run: |
          copy env.vs2022.bat env.bat

      - name: Cache Boost
        id: cache-boost
        uses: actions/cache@v3
        with:
          path: |
            ${{ env.BOOST_ROOT }}.7z
            ${{ env.BOOST_ROOT }}\stage
          key: ${{ runner.os }}-boost-${{ env.boost_version }}

      - name: Extract Boost source tarball
        if: steps.cache-boost.outputs.cache-hit == 'true'
        run: |
          pushd deps
          7z x ${{ env.BOOST_ROOT }}.7z
          popd

      - name: Install Boost
        if: steps.cache-boost.outputs.cache-hit != 'true'
        run: .\install-boost.bat

      - name: Check submodules
        run: git submodule > submodule-status

      - name: Cache dependencies
        id: cache-deps
        uses: actions/cache@v3
        with:
          path: |
            bin
            include
            lib
            share
          key: ${{ runner.os }}-deps-${{ hashFiles('submodule-status') }}

      - name: Build dependencies
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: .\build.bat deps

      - name: Build
        run: .\build.bat

      - name: Set version info
        run: |
          echo "librime ${{ github.ref_name }}" >> version-info.txt
          echo $(git ls-tree HEAD:plugins | awk '$2 == "commit" {print $4,$3}') >> version-info.txt

      - name: Create distributable
        run: |
          7z a rime-TypeDuck-${{ github.ref_name }}-${{ runner.os }}.7z `
          dist version-info.txt
          7z a -x'!*/.placeholder' rime-deps-TypeDuck-${{ github.ref_name }}-${{ runner.os }}.7z `
          bin include lib share

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          path: |
            rime-TypeDuck-${{ github.ref_name }}-${{ runner.os }}.7z
            rime-deps-TypeDuck-${{ github.ref_name }}-${{ runner.os }}.7z
